### ISSUE TITLE
Some Postgresql specific queries cause the QUERY_SIGNATURE view to crash

### ISSUE THREAD

**Issue by jur-clerkx** [django-query-profiler/django-query-profiler#21]
Moz parser can't handle certain Postgresql specific queries and returns a `ParseException` (e.g. `SELECT DISTINCT ON` https://www.geekytidbits.com/postgres-distinct-on/).

This results into the `QUERY_SIGNATURE` view to crash when trying to render the recommendation for those queries.

```
ParseException at /django_query_profiler/2caa74b2f946492cade911200a7f7d8a/QUERY_SIGNATURE
Expecting one of (binary_and, binary_or, concat, in, neq, offset, and, left join, inner join, group by, not_between, collate nocase, full join, full outer join, order by, between, is, or, left outer join, right join, nlike, nin, right outer join, union, like, limit, having, join) (at char 134), (line:1, col:135)
```

**Comment by yashmaheshwari** [comment]
Let me take a look in a day or two;  Maybe we should call the parser in try-except block if the parser can't handle it ?

**Comment by yashmaheshwari** [comment]
Can you try the new version (0.7).  It should be fixed now.

**Comment by django-query-profiler** [comment]
Closing this issue.
