### ISSUE TITLE
RecursionError at query-signature

### ISSUE THREAD

**Issue by sajoku** [django-query-profiler/django-query-profiler#23]
I seem to be running into a bug but I'm not really sure on why this fails at the point where it fails. 

RecursionError at /django_query_profiler/7c1ed3533d2a4c91aa3736812dffe345/QUERY_SIGNATURE
maximum recursion depth exceeded while calling a Python object

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/390331/120208528-deab0980-c22d-11eb-904a-5ea4e00409a1.png">

This is in the file: `django_query_profiler/templates/django_query_profiler_level_query_signature.html` line `177`.
If I expand the if statement with `{% if query_signature and query_signature.analysis.visible_in_ui %}`,
this works fine, just does not show the analysis name.

**Comment by yashmaheshwari** [comment]
We are using the Moz parser to parse the sql, and this particular line goes to that code path.  Looks like there is a Recursion error in that code path

Recently fixed [this issue](https://github.com/django-query-profiler/django-query-profiler/issues/21) with try-except block [here](https://github.com/django-query-profiler/django-query-profiler/pull/22/files#diff-5047014d066bf16e5cd5e8f1b5b2c54f0b7f93e79f6d1d79ec06de75539509eeR78)
Looks like we should not only catch ParseException, but Exception base class

The idea with this code is to help with recommendations - whether its a simple case of applying select_related or prefetch_related;  Its better to show no recommendations than fail

Let me try to take a stab at it today.

**Comment by yashmaheshwari** [comment]
Can you try with the latest version (0..8).  I believe it should fix this issue;

**Comment by sajoku** [comment]
> Can you try with the latest version (0..8). I believe it should fix this issue;

Yes this works 🙂 Thanks for fixing this that fast 🙏🏻
