### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'DJANGO_QUERY_PROFILER_REDIS_HOST'

### ISSUE THREAD

**Issue by TheVinhLuong102** [django-query-profiler/django-query-profiler#25]
Hi Django Query Profiler authors,

I've come across this project while looking for a solution for the current state of limbo at Django-Silk (https://github.com/jazzband/django-silk/issues/465). :)

I've installed the package and configured `settings.py` and `urls.py` per https://django-query-profiler.readthedocs.io/en/latest/configuration_instructions.html. However, I hit this error `AttributeError: 'Settings' object has no attribute 'DJANGO_QUERY_PROFILER_REDIS_HOST'` when running the server.

Could you let me know how I can overcome this problem?

Thank you very much!

Vinh

**Comment by dmartin** [comment]
Are you sure you added the

```python
from django_query_profiler.settings import *
```

import to your `settings.py`? That should import the default `DJANGO_QUERY_PROFILER_REDIS_HOST` variable.

**Comment by TheVinhLuong102** [comment]
@dmartin,

Thank you very much.

It was my bad -- I was so focused on the changed to the setting attributes themselves that the `from django_query_profiler.settings import *` totally fell into my blindspot!! :)

This resolves it.

I'll test out this cool tool. Thanks for building this.

Vinh

**Comment by dmartin** [comment]
Oh, I'm not an author and I don't want to take any credit. Just happened to see your issue. Glad you got it working!

**Comment by TheVinhLuong102** [comment]
@dmartin thank you even more -- for not being a bystander! :D
