### ISSUE TITLE
It relies on moz-sql-parser, which has already been archived and deprecated.

### ISSUE THREAD

**Issue by Taikono-Himazin** [django-query-profiler/django-query-profiler#26]
It relies on moz-sql-parser, which has already been archived and deprecated.
https://github.com/mozilla/moz-sql-parser
Is there any attempt to make this the successor mo-sql-parsing?
https://github.com/klahnakoski/mo-sql-parsing

I looked at the source code for an hour trying to do this, but I wasn't sure. sorry.

**Comment by yashmaheshwari** [comment]
Hey Taikono,

Thanks for pointing that out.  I wasn't aware of it -- I would read more about this new package over the weekend, and would see if we can use the forked package

The other thing I had in mind was testing with Django 4.0 as well

**Comment by yashmaheshwari** [comment]
This was pushed to master, and is fixed in the latest version (0.9)
Was getting some exceptions when trying to use for Django 4.0 - so would be doing that as part of the next PR;

Closing
